<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-3POOLFT" failures="1" tests="2" name="testcase" time="9.845" errors="0" timestamp="2024-03-27T13:51:35 IST">
  <testcase classname="TestNGDemos.TestcaseforListenersexec" name="Testcase1" time="0.334">
    <failure type="java.lang.AssertionError" message="expected [null] but found [https://practicetestautomation.com/practice-test-login/]">
      <![CDATA[java.lang.AssertionError: expected [null] but found [https://practicetestautomation.com/practice-test-login/]
at TestNGDemos.TestcaseforListenersexec.Testcase1(TestcaseforListenersexec.java:30)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- Testcase1 -->
  <testcase classname="TestNGDemos.TestcaseforListenersexec" name="Testcase2" time="1.202"/>
</testsuite> <!-- testcase -->
